/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.github.tuczv.addressBook.api;

import com.github.tuczv.addressBook.api.dto.ErrorApiDto;
import com.github.tuczv.addressBook.api.dto.MessageApiDto;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
public interface ChatV1Api {

    /**
     * POST /v1/messages : Post a message.
     *
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/messages",
        produces = { "application/json" }
    )
    ResponseEntity<MessageApiDto> createMessage(
        
    );


    /**
     * GET /v1/messages : Get a messages. Results are pageable with seek method.
     *
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/messages",
        produces = { "application/json" }
    )
    ResponseEntity<List<MessageApiDto>> findMessages(
        
    );

}
