/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.github.tuczv.addressBook.api;

import com.github.tuczv.addressBook.api.dto.ContactApiDto;
import com.github.tuczv.addressBook.api.dto.ErrorApiDto;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
public interface ContactsV1Api {

    /**
     * POST /v1/contacts : Add new contact.
     *
     * @param contactApiDto  (required)
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/contacts",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<List<ContactApiDto>> createContact(
         @Valid @RequestBody ContactApiDto contactApiDto
    );


    /**
     * GET /v1/contacts/group/{groupName} : Get a contacts by group. Results are pageable with seek method.
     *
     * @param groupName Group name (required)
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/contacts/group/{groupName}",
        produces = { "application/json" }
    )
    ResponseEntity<List<ContactApiDto>> findContactByGroup(
         @PathVariable("groupName") UUID groupName
    );


    /**
     * GET /v1/contacts/{contactId} : Get a contact by id. Results are pageable with seek method.
     *
     * @param contactId Contact Id (required)
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/contacts/{contactId}",
        produces = { "application/json" }
    )
    ResponseEntity<ContactApiDto> findContactById(
         @PathVariable("contactId") UUID contactId
    );


    /**
     * GET /v1/contacts : Get contacts. Results are pageable with seek method.
     *
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/contacts",
        produces = { "application/json" }
    )
    ResponseEntity<List<ContactApiDto>> findContacts(
        
    );


    /**
     * DELETE /v1/contacts/{contactId} : Delete a contact by id.
     *
     * @param contactId Contact Id (required)
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/v1/contacts/{contactId}",
        produces = { "application/json" }
    )
    ResponseEntity<ContactApiDto> removeContactById(
         @PathVariable("contactId") UUID contactId
    );


    /**
     * PUT /v1/contacts/{contactId} : Update a contact by id.
     *
     * @param contactId Contact Id (required)
     * @param contactApiDto  (required)
     * @return OK (status code 200)
     *         or error (status code 400)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/v1/contacts/{contactId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ContactApiDto> updateContactById(
         @PathVariable("contactId") UUID contactId,
         @Valid @RequestBody ContactApiDto contactApiDto
    );

}
